version: "3.0"
services:

  database:
    container_name: facebookly-db
    image: mysql:8.0.33
    ports:
      - "3309:3306"
    networks:
      - facebookly-net
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
      - facebookly-data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: facebookly

  api:
    container_name: facebookly-api
    image: piotrpiw/facebookly-api:5.0
    build: .
    ports:
      - "8080:8080"
    networks:
      - facebookly-net
    restart: always
    depends_on:
      - database
    environment:
      MYSQL_HOST: facebookly-db
      MYSQL_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PORT: 3306
      MYSQL_DATABASE: facebookly

networks:
  facebookly-net:
    driver: bridge

volumes:
  facebookly-data:

