insert into USERS (first_name, last_name, gender, email, login, password) values ('Vilhelmina', 'Fabb', 'Female', 'vfabb0@lulu.com', 'vfabb0', 'wB7"Ev\>Gs06g');
insert into USERS (first_name, last_name, gender, email, login, password) values ('Stephi', 'Doe', 'Female', 'sdoe1@blogger.com', 'sdoe1', 'wC1+`R3sS0K<s');
insert into USERS (first_name, last_name, gender, email, login, password) values ('Karena', 'Shales', 'Female', 'kshales2@wix.com', 'kshales2', 'fQ3''YM#WlD)wE');
insert into USERS (first_name, last_name, gender, email, login, password) values ('Ezechiel', 'Blabie', 'Male', 'eblabie3@tumblr.com', 'eblabie3', 'bS4"5~8/MT&');
insert into USERS (first_name, last_name, gender, email, login, password) values ('Sarena', 'Richemond', 'Female', 'srichemond4@psu.edu', 'srichemond4', 'bB7>6x<$nfjlC<');
insert into USERS (first_name, last_name, gender, email, login, password) values ('Rhianon', 'Letch', 'Female', 'rletch5@google.ru', 'rletch5', 'oV7/t''D""2');
insert into USERS (first_name, last_name, gender, email, login, password) values ('Blondie', 'Lean', 'Female', 'blean6@joomla.org', 'blean6', 'kD7)<7b?f>');
insert into USERS (first_name, last_name, gender, email, login, password) values ('Ernst', 'Skerm', 'Male', 'eskerm7@msu.edu', 'eskerm7', 'dY5(Ja,l><K7Q>B');
insert into USERS (first_name, last_name, gender, email, login, password) values ('Eddie', 'Rudsdell', 'Female', 'erudsdell8@ustream.tv', 'erudsdell8', 'aS0{uliWv.?');
insert into USERS (first_name, last_name, gender, email, login, password) values ('Meredith', 'Greenard', 'Female', 'mgreenard9@prlog.org', 'mgreenard9', 'kB5{%}l=*.y~.X_');





insert into POSTS (content, created, image, user_id) values ('Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2023-02-09 00:19:23', '/Users/piotrpiwowarski/Desktop', 10);
insert into POSTS (content, created, user_id) values ('In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', '2023-08-18 07:06:46', 10);
insert into POSTS (content, created, user_id) values ('Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', '2023-05-31 06:33:35', 3);
insert into POSTS (content, created, user_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2023-08-02 11:30:48', 2);
insert into POSTS (content, created, user_id) values ('Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', '2023-04-25 12:43:43', 4);
insert into POSTS (content, created, user_id) values ('Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '2023-07-04 08:40:20', 8);
insert into POSTS (content, created, user_id) values ('Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', '2023-07-02 15:43:36', 8);
insert into POSTS (content, created, user_id) values ('Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '2023-05-17 20:22:02', 7);
insert into POSTS (content, created, user_id) values ('Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '2023-05-14 10:07:20', 2);
insert into POSTS (content, created, user_id) values ('Ut at dolor quis odio consequat varius.', '2022-10-09 07:29:03', 1);
insert into POSTS (content, created, user_id) values ('Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.', '2023-01-30 10:01:46', 5);
insert into POSTS (content, created, user_id) values ('Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', '2022-12-03 23:46:36', 4);
insert into POSTS (content, created, user_id) values ('Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2023-08-02 13:58:00', 7);
insert into POSTS (content, created, user_id) values ('Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', '2023-02-21 13:37:56', 6);
insert into POSTS (content, created, user_id) values ('Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2023-05-19 11:20:30', 7);
insert into POSTS (content, created, user_id) values ('Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '2023-02-26 22:15:19', 3);
insert into POSTS (content, created, user_id) values ('Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', '2023-06-16 20:23:26', 7);
insert into POSTS (content, created, user_id) values ('Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', '2022-12-12 01:17:32', 4);
insert into POSTS (content, created, user_id) values ('Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', '2022-11-22 18:22:42', 1);
insert into POSTS (content, created, user_id) values ('Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', '2023-09-02 07:28:45', 8);





insert into COMMENTS (content, created, user_id, post_id) values ('Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2023-01-06 03:09:07', 1, 20);
insert into COMMENTS (content, created, user_id, post_id) values ('Nulla ac enim.', '2022-12-17 21:46:39', 8, 19);
insert into COMMENTS (content, created, user_id, post_id) values ('Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', '2023-01-24 05:00:49', 9, 14);
insert into COMMENTS (content, created, user_id, post_id) values ('Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2023-09-18 20:31:31', 9, 3);
insert into COMMENTS (content, created, user_id, post_id) values ('Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2022-10-21 11:33:04', 6, 1);
insert into COMMENTS (content, created, user_id, post_id) values ('Nulla suscipit ligula in lacus.', '2023-05-25 16:04:16', 9, 5);
insert into COMMENTS (content, created, user_id, post_id) values ('Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.', '2023-02-02 19:24:47', 2, 2);
insert into COMMENTS (content, created, user_id, post_id) values ('Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.', '2023-02-19 23:43:03', 1, 7);
insert into COMMENTS (content, created, user_id, post_id) values ('Vivamus tortor. Duis mattis egestas metus.', '2022-11-16 13:28:05', 5, 17);
insert into COMMENTS (content, created, user_id, post_id) values ('Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', '2023-02-25 20:11:39', 1, 5);
insert into COMMENTS (content, created, user_id, post_id) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '2023-02-10 10:17:57', 9, 6);
insert into COMMENTS (content, created, user_id, post_id) values ('Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', '2023-02-05 14:47:09', 3, 10);
insert into COMMENTS (content, created, user_id, post_id) values ('Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2023-01-01 10:50:10', 9, 19);
insert into COMMENTS (content, created, user_id, post_id) values ('Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2023-02-24 05:08:32', 8, 16);
insert into COMMENTS (content, created, user_id, post_id) values ('In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2022-12-14 20:17:51', 10, 9);
insert into COMMENTS (content, created, user_id, post_id) values ('Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '2023-06-09 05:12:29', 8, 7);
insert into COMMENTS (content, created, user_id, post_id) values ('Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2022-10-06 07:43:22', 1, 1);
insert into COMMENTS (content, created, user_id, post_id) values ('Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '2023-03-29 22:07:35', 8, 4);
insert into COMMENTS (content, created, user_id, post_id) values ('Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.', '2023-04-27 10:38:05', 1, 8);
insert into COMMENTS (content, created, user_id, post_id) values ('Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', '2023-06-26 03:18:51', 7, 18);
insert into COMMENTS (content, created, user_id, post_id) values ('Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.', '2023-05-06 14:25:29', 5, 17);
insert into COMMENTS (content, created, user_id, post_id) values ('Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '2022-10-21 20:16:40', 6, 15);
insert into COMMENTS (content, created, user_id, post_id) values ('Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2023-06-28 20:39:57', 7, 9);
insert into COMMENTS (content, created, user_id, post_id) values ('Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '2023-07-30 02:32:09', 5, 2);
insert into COMMENTS (content, created, user_id, post_id) values ('Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2023-08-29 18:36:15', 10, 1);
insert into COMMENTS (content, created, user_id, post_id) values ('Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '2022-12-01 16:02:09', 1, 18);
insert into COMMENTS (content, created, user_id, post_id) values ('Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2023-05-14 12:02:19', 2, 20);
insert into COMMENTS (content, created, user_id, post_id) values ('Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2022-12-04 23:05:08', 1, 14);
insert into COMMENTS (content, created, user_id, post_id) values ('Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', '2023-01-27 00:03:30', 4, 17);
insert into COMMENTS (content, created, user_id, post_id) values ('Sed accumsan felis.', '2023-02-24 20:06:41', 5, 3);